name: "Hello actions"
description: "Greet someone"
author: "octocat@github.com"

inputs: 
  MY_NAME:
    description: "Who to greet"
    required: true
    defult: "World"

runs:
  using: "docker"
  image: "dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
